CREATE TABLE "brands" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" NOT NULL,
  "parent_id" BIGINT
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" "VARCHAR(255)" NOT NULL,
  "brand_id" BIGINT NOT NULL,
  "category_id" BIGINT NOT NULL,
  "price" INT NOT NULL DEFAULT 0,
  "discount_rate" INT NOT NULL DEFAULT 0,
  "rating" INT NOT NULL DEFAULT 0,
  "review_count" INT NOT NULL DEFAULT 0,
  "image_url" TEXT,
  "source" "VARCHAR(50)" NOT NULL,
  "source_url" TEXT,
  "created_at" "DATETIME" DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "main_banners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(255)" NOT NULL,
  "subtitle" "VARCHAR(255)",
  "image_url" TEXT,
  "link_url" TEXT,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "main_sections" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(100)" NOT NULL,
  "section_type" "VARCHAR(50)" NOT NULL,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "main_section_products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "display_order" INT NOT NULL DEFAULT 0
);

CREATE TABLE "quick_menus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" NOT NULL,
  "icon_url" TEXT,
  "link_url" TEXT,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

ALTER TABLE "categories" ADD CONSTRAINT "fk_category_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT "fk_product_brand" FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main_section_products" ADD CONSTRAINT "fk_section_product_section" FOREIGN KEY ("section_id") REFERENCES "main_sections" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main_section_products" ADD CONSTRAINT "fk_section_product_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;
