CREATE TABLE "brands" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" NOT NULL,
  "parent_id" BIGINT
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" "VARCHAR(255)" NOT NULL,
  "brand_id" BIGINT NOT NULL,
  "category_id" BIGINT NOT NULL,
  "price" INT NOT NULL DEFAULT 0,
  "gender" "VARCHAR(10)" NOT NULL DEFAULT 'UNISEX',
  "discount_rate" INT NOT NULL DEFAULT 0,
  "rating" INT NOT NULL DEFAULT 0,
  "review_count" INT NOT NULL DEFAULT 0,
  "image_url" TEXT,
  "source" "VARCHAR(50)" NOT NULL,
  "source_url" TEXT,
  "created_at" "DATETIME" DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "main_banners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(255)" NOT NULL,
  "subtitle" "VARCHAR(255)",
  "image_url" TEXT,
  "link_url" TEXT,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "main_sections" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(100)" NOT NULL,
  "section_type" "VARCHAR(50)" NOT NULL,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "main_section_products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "display_order" INT NOT NULL DEFAULT 0
);

CREATE TABLE "quick_menus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" NOT NULL,
  "icon_url" TEXT,
  "link_url" TEXT,
  "display_order" INT NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" "VARCHAR(255)" UNIQUE NOT NULL,
  "password" "VARCHAR(255)",
  "name" "VARCHAR(100)" NOT NULL,
  "nickname" "VARCHAR(100)" UNIQUE NOT NULL,
  "phone" "VARCHAR(20)",
  "profile_image_url" TEXT,
  "default_address" TEXT,
  "role" "VARCHAR(20)" NOT NULL DEFAULT 'ROLE_USER',
  "provider" "VARCHAR(20)" NOT NULL DEFAULT 'LOCAL',
  "provider_id" "VARCHAR(255)",
  "created_at" "DATETIME" NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" "DATETIME"
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT UNIQUE NOT NULL
);

CREATE TABLE "product_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" BIGINT NOT NULL,
  "option_name" "VARCHAR(100)" NOT NULL,
  "stock_quantity" INT NOT NULL DEFAULT 0,
  "additional_price" INT NOT NULL DEFAULT 0,
  "status" "VARCHAR(20)" NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "option_id" BIGINT NOT NULL,
  "quantity" INT NOT NULL DEFAULT 1
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_no" "VARCHAR(30)" UNIQUE,
  "user_id" BIGINT NOT NULL,
  "status" "VARCHAR(20)" NOT NULL DEFAULT 'PENDING',
  "total_amount" INT NOT NULL DEFAULT 0,
  "receiver_name" "VARCHAR(100)",
  "zip_code" "VARCHAR(10)",
  "address" TEXT,
  "phone" "VARCHAR(20)",
  "created_at" "DATETIME" NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" BIGINT NOT NULL,
  "product_id" BIGINT,
  "option_id" BIGINT,
  "snapshot_name" "VARCHAR(255)" NOT NULL,
  "snapshot_price" INT NOT NULL,
  "snapshot_option_name" "VARCHAR(100)",
  "snapshot_image_url" TEXT,
  "quantity" INT NOT NULL
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" BIGINT UNIQUE NOT NULL,
  "user_id" BIGINT NOT NULL,
  "payment_key" "VARCHAR(255)" UNIQUE,
  "amount" INT NOT NULL,
  "method" "VARCHAR(50)",
  "status" "VARCHAR(20)" NOT NULL DEFAULT 'READY',
  "approved_at" "DATETIME",
  "canceled_at" "DATETIME",
  "cancel_reason" "VARCHAR(255)",
  "canceled_amount" INT NOT NULL DEFAULT 0,
  "fail_reason" "VARCHAR(255)",
  "created_at" "DATETIME" NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "wishes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "created_at" "DATETIME" NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "recent_view_products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "viewed_at" "DATETIME" NOT NULL
);

ALTER TABLE "categories" ADD CONSTRAINT "fk_category_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT "fk_product_brand" FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main_section_products" ADD CONSTRAINT "fk_section_product_section" FOREIGN KEY ("section_id") REFERENCES "main_sections" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main_section_products" ADD CONSTRAINT "fk_section_product_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD CONSTRAINT "fk_cart_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_options" ADD CONSTRAINT "fk_product_option_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_item_cart" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_item_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_item_option" FOREIGN KEY ("option_id") REFERENCES "product_options" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD CONSTRAINT "uk_cart_item_cart_product_option" UNIQUE ("cart_id", "product_id", "option_id");

ALTER TABLE "orders" ADD CONSTRAINT "fk_order_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_item_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_item_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_item_option" FOREIGN KEY ("option_id") REFERENCES "product_options" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD CONSTRAINT "fk_payment_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD CONSTRAINT "fk_payment_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishes" ADD CONSTRAINT "fk_wish_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishes" ADD CONSTRAINT "fk_wish_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishes" ADD CONSTRAINT "uk_wish_user_product" UNIQUE ("user_id", "product_id");

ALTER TABLE "recent_view_products" ADD CONSTRAINT "fk_recentview_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recent_view_products" ADD CONSTRAINT "fk_recentview_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recent_view_products" ADD CONSTRAINT "uk_recentview_user_product" UNIQUE ("user_id", "product_id");
